### ISSUE TITLE
Bad naming of function `is_synchronized/0`

### ISSUE THREAD

**Issue by brodeuralexis** [fhunleth/nerves_time#2]
As per the [Elixir Naming Conventions](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Naming%20Conventions.md#is_-prefix-is_foo), `is_synchronized/0` should be renamed to `synchronized?/0`.

TL;DR.: Only functions that check types and are allowed in guard clauses can start with `is_`.

**Comment by fhunleth** [comment]
Thanks for catching that!

**Comment by brodeuralexis** [comment]
Happy to help !
