### ISSUE TITLE
Issues connecting through wifi

### ISSUE THREAD

**Issue by stwf** [fhunleth/nerves_time#6]
I've added nerves_time to my nerves project but it doesn't sync the clock up. The feature that it saves the last time and restores it on startup does work, but the time isn't synced. Running on an RPI0W. Connecting to the network through WiFi.

When looking at the log, I do see the call:

```
20:12:23.181 [debug] Starting ntpd as: ["/usr/sbin/ntpd", "-n", "-d", "-S", "/srv/erlang/lib/nerves_time-0.2.0/priv/ntpd_script", "-p", "0.pool.ntp.org", "-p", "1.po
ol.ntp.org", "-p", "2.pool.ntp.org", "-p", "3.pool.ntp.org"]

```
But it happens long before the network is initialized and I don't see it again. I'm not sure if its supposed to timeout but I've waited a while and it doesn't get set. A call to Nerves.Time.synchronized? returns false.
A manual call to Nerves.Time.Ntpd.restart_ntpd() does sync up the clock correctly and after that Nerves.Time.synchronized? returns true.

I'm using nerves_init_gadget to set up my network, and setting a host name, so it seems to take 30-45 seconds for the network to initialize.

Thanks!

**Comment by stwf** [comment]
fwiw, I'm working around it with the following snippet I stole from somewhere...

```
defmodule MyApp.Application do
  use Application
  require Logger

  def start(_type, _args) do
    import Supervisor.Spec, warn: false
    iface = Application.get_env(:nerves_init_gadget, :ifname)
    children = [
      worker(
        SystemRegistry.Task,
        [[:state, :network_interface, iface, :ipv4_address], &init_network/1]
      )
    ]
    opts = [strategy: :one_for_one, name: MyApp.Supervisor]
    Supervisor.start_link(children, opts)
  end

  def init_network(delta) do
    Logger.info("network initialized - init_network #{inspect(delta)}")
    Nerves.Time.restart_ntpd()
  end
```

**Comment by stwf** [comment]
New interesting point.
I fixed the issue. The problem seems to be caused by me having nerves_init_gadget set to be opened by Shoehorn. It crept into my code from an earlier project that needed internet access when it booted, but I took it out of this project and sure enough nerves_time worked correctly.
So I'm not sure if thats helps with a solution, or if nerves_init_gadget just shouldn't be launched by Shoehorn.

**Comment by fhunleth** [comment]
Thanks for the updates. I'm planning on taking a pass on `nerves_time` to improve a few things, but it's looking like that will be after ElixirConf. My experience so far has been that time eventually updates, but sometimes it takes much longer than you'd expect. I'll keep this issue in mind when I get back to it.

**Comment by stwf** [comment]
you're busy ??? ;-)
Another corner case I noticed. If it doesn't connect to a network, the previous synced time recorded will be picked up from the .nerves_time file, and the clock will not be to far off. 
But from that point on the .nerves_time file that records the current time doesn't seem to be written. So subsequent reboots revert back to the last synced time. Which I sort of understand, but since we know the machine has been running and time has passed, even an unsynced time would be more accurate than the last synced time?

**Comment by fhunleth** [comment]
So sorry - I missed your comment here from last year. 

Reboots clear out the time completely. The system boots to 1/1/1970 and `nerves_time` moves it closer to the real time based on the earliest allowed time and the `.nerves_time` file. From then, `ntpd` is needed to move it closer to the actual time. "Unsynced" time is 1970, so it's not that helpful. The only practical way to keep time across a reboot is to use an RTC. I hope we have support for that at some point.
